#person:
#  lastName: ANDY
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1, k2: 12}
#  lists:
#   - Henry
#   - Donna
#  dog:
#    name: Lucy
#    age: 12
spring:  profiles:    active: testYml1
---

spring:  profiles:  testYml1
  
server:  port: 8077
  
---

spring:
  profiles:  testYml2

server:
  port: 8078
  
---

spring:
  profiles:  testYml3
  
server:
  port: 8079
  
 